# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.24)
{
  # A helpful description of your flake
  description = "CI/CD with flake";

  # Flake inputs
  inputs = { nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.05"; };

  # Flake outputs that other flakes can use
  outputs = { self, nixpkgs }:
    let
      # Helpers for producing system-specific outputs
      supportedSystems = [ "x86_64-linux" ];
      forEachSupportedSystem = f:
        nixpkgs.lib.genAttrs supportedSystems (system:
          f {
            pkgs = import nixpkgs {
              inherit system;

              config = {
                allowUnfree = true;
                permittedInsecurePackages = [
                  "nodejs-16.20.2"
                ];
              };
            };
          });
    in {
      # Development environments
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          # Pinned packages available in the environment
          packages = with pkgs; [ nodejs_16 ];

          shellHook = ''
            echo "✔ Node.js version: $(node -v)"
            echo "✔ NPM version: $(npm -v)"
          '';
        };
      });
    };
}
