on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dummy deploy
        if: ${{ github.event_name == 'push' }}
        run: echo "🚀 Dummy deploying to production"
