name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Run tests
        run: npm test

    # Notify on success
    if: ${{ success() }}
    steps:
      - name: Send Discord success message
        uses: Ilshidur/action-discord@master
        with:
          args: |
            ✅ **Build succeeded**
            Commit: ${{ github.sha }}
            [View commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}


    # Notify on failure
    if: ${{ failure() }}
    steps:
      - name: Send Discord failure message
        uses: Ilshidur/action-discord@master
        with:
          args: |
            ❌ **Build failed**
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            Message: "${{ github.event.head_commit.message }}"
            [View commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
